name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Validate JSON rules
        run: npm run validate:rules

      - name: Consistency check
        run: npm run check

      - name: Start static server
        run: npx http-server -p 5500 -c-1 &

      - name: Smoke
        env:
          BASE_URL: http://127.0.0.1:5500
        run: node scripts/smoke.mjs
